trigger:
- master

variables:
  tag: '$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
     - job: Build
       displayName: Build job
       pool: 
         vmImage: 'ubuntu-latest'
       steps:
         # Task-1: Build Docker Image and push to Azure Container Registry ACR
         - task: Docker@2
           inputs:
             containerRegistry: 'alphamkusacr'
             repository: 'app1'
             command: 'buildAndPush'
             Dockerfile: '**/Dockerfile'
         - task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/kube-manifests'
            ArtifactName: 'drop'
            publishLocation: 'Container'
